### Archive Trace 

### Get all archive
GET http://localhost:3000/api/v1/image/archive

### Create an archive 
POST http://localhost:3000/api/v1/image/archive
Content-Type: application/json

{
  "description": "Stars, staring and shinning on us over centries, can only be seen in dark nights."
}

### Update an archive
PUT http://localhost:3000/api/v1/image/archive/21
Content-Type: application/json

{
  "action": "remove", 
  "ids": [ 3, 5 ]
}

### Delete an archive
DELETE http://localhost:3000/api/v1/image/archive/10


# 
# REST Client for Visual Studio Code
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#